import { Check, Info, ShieldCheck } from "lucide-react";
import { useLanguage } from "../../app/PreferencesContext";
import { localise, t } from "../../lib/i18n";
import type { ComparisonTable, DefensiveChecklist, Diagram, PracticalExample } from "../../types/content";

export function ConceptDiagram({ diagram }: { diagram: Diagram }) {
  const language = useLanguage();
  const tone: Record<string, string> = { green: "border-scope-400 bg-scope-50 dark:bg-scope-950/50", blue: "border-sky-400 bg-sky-50 dark:bg-sky-950/30", amber: "border-amber-400 bg-amber-50 dark:bg-amber-950/30", red: "border-red-400 bg-red-50 dark:bg-red-950/30" };
  return <figure className="panel industrial-grid my-8 overflow-hidden p-5 sm:p-7" aria-labelledby={`${diagram.id}-title`}><figcaption><span className="eyebrow">{t("diagram", language)}</span><h2 id={`${diagram.id}-title`} className="mt-2 text-xl font-bold text-slate-950 dark:text-white">{localise(diagram.title, language)}</h2><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{localise(diagram.description, language)}</p></figcaption><div className="diagram-flow mt-6 grid gap-6 sm:grid-cols-2 xl:grid-cols-4">{diagram.nodes.map(node => <div key={node.id} className={`relative min-h-28 rounded-xl border-l-4 p-4 shadow-sm ${tone[node.tone ?? "green"]}`}><h3 className="text-sm font-bold text-slate-950 dark:text-white">{localise(node.label, language)}</h3><p className="mt-2 text-xs leading-5 text-slate-600 dark:text-slate-300">{localise(node.detail, language)}</p></div>)}</div><p className="mt-6 flex gap-2 border-t border-slate-200 pt-4 text-xs leading-5 text-slate-500 dark:border-white/10 dark:text-slate-400"><Info size={15} className="mt-0.5 shrink-0" />{localise(diagram.caption, language)}</p></figure>;
}

export function Comparison({ table }: { table: ComparisonTable }) { const language = useLanguage(); return <section className="my-8"><span className="eyebrow">{t("compare", language)}</span><h2 className="mt-2 text-xl font-bold text-slate-950 dark:text-white">{localise(table.title, language)}</h2><div className="mt-4 overflow-x-auto rounded-2xl border border-slate-200 dark:border-white/10"><table className="w-full min-w-[640px] border-collapse text-left text-sm"><thead className="bg-slate-100 dark:bg-white/5"><tr>{table.columns.map((column, index) => <th key={index} scope="col" className="px-4 py-3 font-semibold text-slate-800 dark:text-slate-100">{localise(column, language)}</th>)}</tr></thead><tbody className="divide-y divide-slate-200 bg-white dark:divide-white/10 dark:bg-[#151b17]">{table.rows.map((row, rowIndex) => <tr key={rowIndex}>{row.map((cell, cellIndex) => <td key={cellIndex} className={`px-4 py-3 leading-6 text-slate-600 dark:text-slate-300 ${cellIndex === 0 ? "font-semibold text-slate-950 dark:text-white" : ""}`}>{localise(cell, language)}</td>)}</tr>)}</tbody></table></div></section>; }

export function Checklist({ checklist }: { checklist: DefensiveChecklist }) { const language = useLanguage(); return <aside className="my-8 rounded-2xl border border-scope-300 bg-scope-50 p-5 dark:border-scope-800 dark:bg-scope-950/30"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-scope-500 text-[#07150b]"><ShieldCheck size={20} /></span><div><span className="eyebrow">{t("checklist", language)}</span><h2 className="mt-1 text-lg font-bold text-slate-950 dark:text-white">{localise(checklist.title, language)}</h2></div></div><ul className="mt-5 grid gap-3 sm:grid-cols-2">{checklist.items.map((item, index) => <li key={index} className="flex gap-3 text-sm leading-6 text-slate-700 dark:text-slate-200"><span className="mt-1 grid size-5 shrink-0 place-items-center rounded-full border border-scope-500 text-scope-700 dark:text-scope-300"><Check size={12} /></span>{localise(item, language)}</li>)}</ul><p className="mt-5 text-xs text-slate-500 dark:text-slate-400">{localise(checklist.note, language)}</p></aside>; }

export function Example({ example }: { example: PracticalExample }) { const language = useLanguage(); return <aside className="panel my-8 overflow-hidden border-l-4 border-l-amber-400 p-5"><span className="eyebrow">{t("practicalExample", language)}</span><h2 className="mt-2 text-lg font-bold text-slate-950 dark:text-white">{localise(example.title, language)}</h2><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{localise(example.scenario, language)}</p><dl className="mt-4 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs font-bold uppercase tracking-wider text-slate-500">{t("response", language)}</dt><dd className="mt-1 text-sm leading-6 text-slate-700 dark:text-slate-200">{localise(example.response, language)}</dd></div><div><dt className="text-xs font-bold uppercase tracking-wider text-slate-500">{t("outcome", language)}</dt><dd className="mt-1 text-sm leading-6 text-slate-700 dark:text-slate-200">{localise(example.outcome, language)}</dd></div></dl></aside>; }
