import { Bookmark, BookOpen, ChevronRight, Info, Menu, Search, Settings, X } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, NavLink, Outlet, useLocation } from "react-router-dom";
import { useLanguage } from "../../app/PreferencesContext";
import { categories } from "../../content/categories";
import { localise, t } from "../../lib/i18n";
import { LanguageSwitch, ThemeControl } from "../settings/PreferenceControls";
import { Brand } from "../ui/Brand";

const linkClass = ({ isActive }: { isActive: boolean }) => `group flex min-h-10 items-center gap-3 rounded-xl px-3 text-sm font-medium transition ${isActive ? "bg-scope-100 text-scope-900 dark:bg-scope-900/50 dark:text-scope-200" : "text-slate-600 hover:bg-slate-100 hover:text-slate-950 dark:text-slate-400 dark:hover:bg-white/5 dark:hover:text-white"}`;

function SidebarContent({ close }: { close?: () => void }) {
  const language = useLanguage();
  return <><div className="flex h-20 items-center justify-between px-5"><Brand />{close && <button onClick={close} className="grid size-10 place-items-center rounded-xl hover:bg-slate-100 dark:hover:bg-white/5" aria-label={t("close", language)}><X size={20} /></button>}</div><nav aria-label={t("navLabel", language)} className="flex-1 overflow-y-auto px-3 pb-6"><div className="space-y-1"><NavLink to="/" end onClick={close} className={linkClass}><span className="size-2 rounded-full bg-scope-500" />{t("home", language)}</NavLink><NavLink to="/explore" onClick={close} className={linkClass}><Search size={16} />{t("explore", language)}</NavLink></div><p className="mb-2 mt-6 px-3 font-mono text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">{t("domains", language)}</p><div className="space-y-1">{categories.map(category => <NavLink key={category.id} to={`/category/${category.slug}`} onClick={close} className={linkClass}><span className="size-2 rounded-full" style={{ backgroundColor: category.accent }} /> <span className="truncate">{localise(category.title, language)}</span><ChevronRight size={14} className="ml-auto opacity-0 transition group-hover:opacity-100" /></NavLink>)}</div><p className="mb-2 mt-6 px-3 font-mono text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">{t("referenceSection", language)}</p><div className="space-y-1"><NavLink to="/glossary" onClick={close} className={linkClass}><BookOpen size={16} />{t("glossary", language)}</NavLink><NavLink to="/saved" onClick={close} className={linkClass}><Bookmark size={16} />{t("saved", language)}</NavLink><NavLink to="/resources" onClick={close} className={linkClass}><Info size={16} />{t("resources", language)}</NavLink><NavLink to="/settings" onClick={close} className={linkClass}><Settings size={16} />{t("settings", language)}</NavLink></div></nav></>;
}

export function AppShell() {
  const [mobileOpen, setMobileOpen] = useState(false); const language = useLanguage(); const location = useLocation();
  useEffect(() => { setMobileOpen(false); window.scrollTo(0, 0); }, [location.pathname]);
  useEffect(() => { if (!mobileOpen) return; const close = (event: KeyboardEvent) => event.key === "Escape" && setMobileOpen(false); addEventListener("keydown", close); return () => removeEventListener("keydown", close); }, [mobileOpen]);
  return <div className="min-h-screen text-slate-900 transition-colors duration-300 dark:text-slate-100">
    <a href="#main-content" className="fixed left-4 top-3 z-[100] -translate-y-20 rounded-lg bg-scope-500 px-4 py-2 font-semibold text-[#07150b] transition focus:translate-y-0">{t("skip", language)}</a>
    <aside className="fixed inset-y-0 left-0 z-40 hidden w-72 flex-col border-r border-slate-200 bg-white dark:border-white/10 dark:bg-[#101512] lg:flex"><SidebarContent /></aside>
    {mobileOpen && <div className="fixed inset-0 z-50 lg:hidden"><button className="absolute inset-0 bg-black/55" onClick={() => setMobileOpen(false)} aria-label={t("close", language)} /><aside className="relative flex h-full w-[min(90vw,22rem)] flex-col bg-white shadow-2xl dark:bg-[#101512]" role="dialog" aria-modal="true"><SidebarContent close={() => setMobileOpen(false)} /></aside></div>}
    <div className="lg:pl-72"><header className="sticky top-0 z-30 flex h-20 items-center gap-3 border-b border-slate-200/80 bg-white/90 px-4 backdrop-blur dark:border-white/10 dark:bg-[#0d110f]/90 sm:px-6"><button onClick={() => setMobileOpen(true)} className="grid size-11 place-items-center rounded-xl border border-slate-200 dark:border-white/10 lg:hidden" aria-label={t("menu", language)}><Menu size={20} /></button><div className="lg:hidden"><Brand compact /></div><Link to="/search" className="button ml-auto hidden sm:flex"><Search size={17} />{t("search", language)} <kbd className="ml-2 rounded border border-slate-200 px-1.5 py-0.5 font-mono text-[10px] text-slate-400 dark:border-white/10">⌘K</kbd></Link><div className="ml-auto sm:ml-0"><ThemeControl /></div><LanguageSwitch /></header><main id="main-content" className="min-h-[calc(100vh-5rem)]"><Outlet /></main><footer className="border-t border-slate-200 px-5 py-8 text-sm text-slate-500 dark:border-white/10 dark:text-slate-400 sm:px-8"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4"><p>CyberScope · {language === "en" ? "Defensive knowledge, locally stored preferences." : "Conocimiento defensivo y preferencias almacenadas localmente."}</p><div className="flex gap-4"><Link to="/privacy" className="hover:text-scope-600">{t("privacy", language)}</Link><Link to="/about" className="hover:text-scope-600">{t("about", language)}</Link></div></div></footer></div>
  </div>;
}
