import { Grid2X2, List, SlidersHorizontal, X } from "lucide-react";
import { useMemo, useState } from "react";
import { useLanguage } from "../app/PreferencesContext";
import { Breadcrumbs } from "../components/content/Breadcrumbs";
import { TopicCard } from "../components/content/TopicCard";
import { SearchBox } from "../components/search/SearchBox";
import { categories } from "../content/categories";
import { topics } from "../content/topics";
import { contentTypeLabel, localise, t, taxonomyLabel } from "../lib/i18n";
import type { ContentType, CyberTopic } from "../types/content";

type FilterKey = "category" | "difficulty" | "contentType" | "environment" | "defensiveFunction" | "technology";
const optionValues = (key: FilterKey) => [...new Set(topics.flatMap(topic => key === "category" ? [topic.category] : key === "difficulty" ? [topic.difficulty] : key === "contentType" ? [topic.contentType] : key === "environment" ? topic.environments : key === "defensiveFunction" ? topic.defensiveFunctions : topic.technologies))].filter(Boolean).sort();

export function ExplorePage() {
  const language = useLanguage(); const [query, setQuery] = useState(""); const [filters, setFilters] = useState<Record<FilterKey, string>>({ category: "", difficulty: "", contentType: "", environment: "", defensiveFunction: "", technology: "" }); const [sort, setSort] = useState("relevance"); const [view, setView] = useState<"grid" | "list">("grid");
  const filtered = useMemo(() => topics.filter(topic => {
    const haystack = [topic.title.en, topic.title.es, topic.summary.en, topic.summary.es, ...topic.aliases, ...topic.tags].join(" ").toLowerCase();
    const matchQuery = query.trim().toLowerCase().split(/\s+/).every(term => haystack.includes(term));
    return matchQuery && (!filters.category || topic.category === filters.category) && (!filters.difficulty || topic.difficulty === filters.difficulty) && (!filters.contentType || topic.contentType === filters.contentType) && (!filters.environment || topic.environments.includes(filters.environment)) && (!filters.defensiveFunction || topic.defensiveFunctions.includes(filters.defensiveFunction)) && (!filters.technology || topic.technologies.includes(filters.technology));
  }).sort((a, b) => sort === "alphabetical" ? localise(a.title, language).localeCompare(localise(b.title, language)) : sort === "difficulty" ? ["introductory", "intermediate", "advanced"].indexOf(a.difficulty) - ["introductory", "intermediate", "advanced"].indexOf(b.difficulty) : 0), [query, filters, sort, language]);
  const set = (key: FilterKey, value: string) => setFilters(current => ({ ...current, [key]: value })); const active = Object.values(filters).filter(Boolean).length;
  const label: Record<FilterKey, ReturnType<typeof t>> = { category: t("domain", language), difficulty: t("difficulty", language), contentType: t("contentType", language), environment: t("environment", language), defensiveFunction: t("defensiveFunction", language), technology: t("technology", language) };
  const renderOption = (key: FilterKey, value: string) => key === "category" ? localise(categories.find(category => category.id === value)?.title ?? { en: value, es: value }, language) : key === "difficulty" ? t(value as "introductory" | "intermediate" | "advanced", language) : key === "contentType" ? contentTypeLabel(value as ContentType, language) : taxonomyLabel(value, language);
  return <div className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><Breadcrumbs items={[{ label: t("explore", language) }]} /><p className="eyebrow">{language === "en" ? "CYBERSCOPE / INDEX" : "CYBERSCOPE / ÍNDICE"}</p><h1 className="page-title">{t("explore", language)}</h1><p className="lead">{language === "en" ? "Search every topic in either language, then narrow the knowledge base by context and defensive purpose." : "Busca cualquier tema en ambos idiomas y acota la base de conocimiento por contexto y finalidad defensiva."}</p><div className="mt-8"><SearchBox large onChange={setQuery} /></div>
    <div className="mt-6 grid gap-6 lg:grid-cols-[17rem_1fr]"><aside className="panel h-fit p-5 lg:sticky lg:top-24"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 font-bold"><SlidersHorizontal size={17} />{t("filters", language)}{active > 0 && <span className="chip">{active}</span>}</h2>{active > 0 && <button onClick={() => setFilters({ category: "", difficulty: "", contentType: "", environment: "", defensiveFunction: "", technology: "" })} className="text-xs font-semibold text-scope-700 dark:text-scope-300">{t("clearFilters", language)}</button>}</div><div className="mt-5 space-y-4">{(Object.keys(filters) as FilterKey[]).map(key => <label className="block" key={key}><span className="mb-1.5 block text-xs font-semibold text-slate-600 dark:text-slate-300">{label[key]}</span><select className="field text-sm" value={filters[key]} onChange={event => set(key, event.target.value)}><option value="">{t("all", language)}</option>{optionValues(key).map(value => <option key={value} value={value}>{renderOption(key, value)}</option>)}</select></label>)}</div></aside>
      <section aria-live="polite"><div className="mb-5 flex flex-wrap items-center gap-3"><p className="mr-auto text-sm text-slate-500 dark:text-slate-400"><strong className="text-slate-900 dark:text-white">{filtered.length}</strong> {t("results", language)}</p><label className="flex items-center gap-2 text-xs font-semibold text-slate-500"><span>{t("sortBy", language)}</span><select className="field min-h-10 w-auto text-sm" value={sort} onChange={event => setSort(event.target.value)}><option value="relevance">{t("relevance", language)}</option><option value="alphabetical">{t("alphabetical", language)}</option><option value="difficulty">{t("difficulty", language)}</option></select></label><div className="flex rounded-xl border border-slate-200 p-1 dark:border-white/10"><button className={`grid size-8 place-items-center rounded-lg ${view === "grid" ? "bg-scope-500 text-[#07150b]" : "text-slate-500"}`} onClick={() => setView("grid")} aria-label={t("gridView", language)} aria-pressed={view === "grid"}><Grid2X2 size={16} /></button><button className={`grid size-8 place-items-center rounded-lg ${view === "list" ? "bg-scope-500 text-[#07150b]" : "text-slate-500"}`} onClick={() => setView("list")} aria-label={t("listView", language)} aria-pressed={view === "list"}><List size={17} /></button></div></div>
      {active > 0 && <div className="mb-4 flex flex-wrap gap-2">{(Object.keys(filters) as FilterKey[]).filter(key => filters[key]).map(key => <button key={key} onClick={() => set(key, "")} className="chip gap-1.5 hover:border-red-400"><span className="font-semibold">{label[key]}:</span> {renderOption(key, filters[key])}<X size={12} /></button>)}</div>}
      {filtered.length ? <div className={view === "grid" ? "grid gap-4 xl:grid-cols-2" : "grid gap-3"}>{filtered.map((topic: CyberTopic) => <TopicCard key={topic.id} topic={topic} list={view === "list"} />)}</div> : <div className="panel grid min-h-64 place-items-center p-8 text-center"><div><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-slate-100 dark:bg-white/5"><X size={22} /></span><h2 className="mt-4 text-xl font-bold">{t("noResults", language)}</h2><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">{t("noResultsHelp", language)}</p><button className="button mt-5" onClick={() => { setQuery(""); setFilters({ category: "", difficulty: "", contentType: "", environment: "", defensiveFunction: "", technology: "" }); }}>{t("clearFilters", language)}</button></div></div>}</section></div>
  </div>;
}
