import type { LocalisedText } from "../types/content";

const l = (en: string, es: string): LocalisedText => ({ en, es });

/**
 * Topic-specific material used to build the long-form explanation of every lesson.
 * These texts deliberately describe the mechanics, scope and boundaries of each topic,
 * rather than repeating a generic security paragraph.
 */
export const topicExplanationDetail: Record<string, LocalisedText> = {
  "cybersecurity": l(
    "It combines technical safeguards with governance, operational discipline and human judgement. Its scope includes devices, networks, software, cloud services, data, suppliers and the physical processes that depend on them; the objective is not to eliminate every threat, but to keep risk within tolerable limits and preserve essential outcomes when prevention fails.",
    "Combina salvaguardas técnicas con gobierno, disciplina operativa y criterio humano. Abarca dispositivos, redes, software, servicios en la nube, datos, proveedores y los procesos físicos que dependen de ellos; su objetivo no es eliminar todas las amenazas, sino mantener el riesgo dentro de límites tolerables y preservar los resultados esenciales cuando la prevención falla."
  ),
  "risk-fundamentals": l(
    "Cyber risk links a possible event to the assets and objectives it could affect. It is assessed by considering credible threat scenarios, existing vulnerabilities and exposure, the likelihood of occurrence, the scale of operational, financial, legal or safety consequences, and the effectiveness of current controls; inherent risk is measured before controls and residual risk after them.",
    "El riesgo cibernético relaciona un suceso posible con los activos y objetivos a los que podría afectar. Se evalúa considerando escenarios de amenaza creíbles, vulnerabilidades y exposición existentes, probabilidad de ocurrencia, alcance de las consecuencias operativas, económicas, legales o de seguridad, y eficacia de los controles actuales; el riesgo inherente se estima antes de los controles y el residual después de aplicarlos."
  ),
  "security-principles": l(
    "Security principles are durable decision rules that help teams design safer systems even when no product or standard gives an exact answer. Least privilege limits authority, need to know restricts access to justified information, segregation of duties prevents one person or account from controlling an entire critical process, and defence in depth ensures that one failed safeguard does not expose the whole service.",
    "Los principios de seguridad son reglas de decisión duraderas que ayudan a diseñar sistemas más seguros incluso cuando ningún producto o norma ofrece una respuesta exacta. El mínimo privilegio limita la autoridad, la necesidad de saber restringe el acceso a información justificada, la segregación de funciones evita que una sola persona o cuenta controle un proceso crítico completo y la defensa en profundidad impide que el fallo de una salvaguarda exponga todo el servicio."
  ),
  "zero-trust": l(
    "Zero Trust replaces implicit trust based on network location with explicit decisions about each request to a protected resource. Identity, device health, workload, requested action, sensitivity, location and current threat signals are evaluated together; access is narrowly scoped, continuously re-evaluated and revoked when conditions change. It is an architectural strategy, not a single product or a synonym for multi-factor authentication.",
    "Zero Trust sustituye la confianza implícita basada en la ubicación de red por decisiones explícitas sobre cada solicitud a un recurso protegido. Se evalúan conjuntamente identidad, estado del dispositivo, carga de trabajo, acción solicitada, sensibilidad, ubicación y señales de amenaza; el acceso se limita al mínimo, se reevalúa de forma continua y se revoca cuando cambian las condiciones. Es una estrategia arquitectónica, no un producto único ni un sinónimo de autenticación multifactor."
  ),
  "threat-modelling": l(
    "Threat modelling examines a system before or during its construction to identify what must be protected, who might attack or misuse it, where trust changes, how data moves and which failures would matter. Methods such as data-flow diagrams, attack trees, misuse cases and structured threat catalogues help teams turn assumptions into testable security requirements and prioritised design changes.",
    "El modelado de amenazas estudia un sistema antes o durante su construcción para identificar qué debe protegerse, quién podría atacarlo o usarlo indebidamente, dónde cambia la confianza, cómo se mueven los datos y qué fallos tendrían consecuencias relevantes. Técnicas como los diagramas de flujo de datos, los árboles de ataque, los casos de abuso y los catálogos estructurados de amenazas convierten supuestos en requisitos de seguridad verificables y cambios de diseño priorizados."
  ),
  "exposure-management": l(
    "Exposure management looks beyond isolated vulnerabilities and asks which weaknesses are actually reachable, combinable and capable of harming an important objective. It continuously joins asset inventory, internet exposure, identity paths, configuration errors, vulnerability intelligence, attacker behaviour and control validation so that remediation is ordered by likely impact rather than by raw finding count.",
    "La gestión de la exposición va más allá de vulnerabilidades aisladas y analiza qué debilidades son realmente alcanzables, combinables y capaces de perjudicar un objetivo importante. Integra de forma continua inventario de activos, exposición a Internet, rutas de identidad, errores de configuración, inteligencia de vulnerabilidades, comportamiento atacante y validación de controles para ordenar la corrección por impacto probable y no por número bruto de hallazgos."
  ),
  "malware": l(
    "Malware is a broad family of malicious programs and scripts designed to execute actions that the legitimate owner did not authorise. A sample may install through a document, browser exploit, stolen account, software update or removable device, then persist, elevate privileges, steal credentials, communicate with command infrastructure, move laterally, encrypt data or sabotage operations. Categories such as trojans, worms, spyware, rootkits and fileless malware describe behaviour or delivery, and a single campaign may combine several of them.",
    "El malware es una familia amplia de programas y scripts maliciosos diseñados para ejecutar acciones que el propietario legítimo no ha autorizado. Puede instalarse mediante un documento, una vulnerabilidad del navegador, una cuenta robada, una actualización de software o un dispositivo extraíble; después puede mantener persistencia, elevar privilegios, robar credenciales, comunicarse con infraestructura de mando, desplazarse lateralmente, cifrar datos o sabotear operaciones. Categorías como troyanos, gusanos, programas espía, rootkits y malware sin archivos describen comportamientos o vías de entrada, y una misma campaña puede combinar varias."
  ),
  "ransomware": l(
    "Modern ransomware is usually a multi-stage intrusion and extortion operation rather than a single encryption program. Attackers obtain access, steal credentials, disable security tooling, discover critical systems, exfiltrate sensitive data and only then encrypt or disrupt services; they may demand payment for restoration, non-publication of stolen data or both. Recovery therefore depends on identity security, containment, clean rebuilds and trustworthy backups, not merely on a decryption key.",
    "El ransomware moderno suele ser una operación de intrusión y extorsión por fases, no un simple programa de cifrado. Los atacantes consiguen acceso, roban credenciales, desactivan herramientas de seguridad, localizan sistemas críticos, extraen datos sensibles y solo después cifran o interrumpen servicios; pueden exigir un pago por la restauración, por no publicar los datos robados o por ambas cosas. Por ello, la recuperación depende de la seguridad de identidades, la contención, la reconstrucción limpia y copias fiables, no solo de una clave de descifrado."
  ),
  "phishing-social-engineering": l(
    "Phishing is one form of social engineering: the attacker creates a believable message, call, website or workflow that causes a person to perform an unsafe action. Campaigns may be broad or highly targeted and can seek passwords, session tokens, payments, confidential information, malware execution or approval of a fraudulent request. The attack succeeds by imitating trusted context and exploiting urgency, authority, curiosity, fear or routine.",
    "El phishing es una modalidad de ingeniería social: el atacante crea un mensaje, llamada, sitio web o flujo de trabajo creíble para inducir a una persona a realizar una acción insegura. Las campañas pueden ser masivas o muy dirigidas y buscar contraseñas, tokens de sesión, pagos, información confidencial, ejecución de malware o aprobación de una solicitud fraudulenta. El ataque funciona al imitar un contexto de confianza y explotar urgencia, autoridad, curiosidad, miedo o rutina."
  ),
  "credential-attacks": l(
    "Credential attacks target passwords, authentication secrets and active sessions rather than the underlying application. Common techniques include password spraying, credential stuffing with passwords leaked elsewhere, brute force, token theft, adversary-in-the-middle phishing, MFA fatigue and reuse of service or API credentials. The decisive question is not only whether a password is strong, but whether identity signals, sessions and recovery channels can resist theft and abuse.",
    "Los ataques contra credenciales se dirigen a contraseñas, secretos de autenticación y sesiones activas en lugar de atacar directamente la aplicación. Entre las técnicas habituales están el password spraying, el relleno de credenciales filtradas en otros servicios, la fuerza bruta, el robo de tokens, el phishing con intermediario, la fatiga de MFA y la reutilización de credenciales de servicios o API. La cuestión decisiva no es solo si una contraseña es robusta, sino si las señales de identidad, las sesiones y los canales de recuperación resisten el robo y el abuso."
  ),
  "network-attacks": l(
    "Network attacks abuse the protocols and trust relationships that allow systems to communicate. They can involve reconnaissance, spoofing, interception, route or name manipulation, denial of service, exploitation of exposed services and lateral movement between reachable hosts. Some attacks alter traffic, others only observe it, and others overwhelm a dependency; understanding topology and protocol state is therefore essential to distinguish legitimate communication from hostile activity.",
    "Los ataques de red abusan de los protocolos y relaciones de confianza que permiten comunicarse a los sistemas. Pueden incluir reconocimiento, suplantación, interceptación, manipulación de rutas o nombres, denegación de servicio, explotación de servicios expuestos y movimiento lateral entre equipos alcanzables. Algunos modifican el tráfico, otros solo lo observan y otros saturan una dependencia; por ello es esencial comprender la topología y el estado de los protocolos para distinguir comunicaciones legítimas de actividad hostil."
  ),
  "intrusion-behaviours": l(
    "Intrusion behaviours describe what an adversary does across the life of a compromise, from initial access and execution to persistence, privilege escalation, defence evasion, discovery, credential access, lateral movement, collection, exfiltration and impact. Organising evidence by behaviour helps defenders connect weak signals from different tools and detect a campaign even when the attacker changes a particular malware family or indicator.",
    "Los comportamientos de intrusión describen lo que hace un adversario durante todo el compromiso: acceso inicial, ejecución, persistencia, elevación de privilegios, evasión de defensas, descubrimiento, acceso a credenciales, movimiento lateral, recopilación, exfiltración e impacto. Organizar la evidencia por comportamiento permite relacionar señales débiles de distintas herramientas y detectar una campaña aunque el atacante cambie de malware o de indicador concreto."
  ),
  "threat-actors": l(
    "A threat actor is a person, group or organisation capable of causing deliberate cyber harm. Actors differ in motive, resources, patience, access and tolerance for risk: financially motivated criminals, state-linked operators, insiders, hacktivists and opportunistic attackers do not choose the same targets or techniques. Actor labels are hypotheses based on evidence and should not be treated as certainty or as a substitute for analysing observable behaviour.",
    "Un actor de amenaza es una persona, grupo u organización capaz de causar daño cibernético deliberado. Los actores difieren en motivación, recursos, paciencia, acceso y tolerancia al riesgo: delincuentes con fines económicos, operadores vinculados a Estados, personas internas, hacktivistas y atacantes oportunistas no seleccionan los mismos objetivos ni técnicas. Las atribuciones son hipótesis basadas en evidencias y no deben tratarse como certezas ni sustituir el análisis del comportamiento observable."
  ),
  "supply-chain-attacks": l(
    "A supply-chain attack compromises a trusted supplier, product, service or update path in order to reach downstream customers. The attacker may alter source code, build systems, packages, firmware, managed-service access or distribution infrastructure, gaining scale and inherited trust. These incidents are difficult because the malicious activity can arrive through a component that has passed ordinary procurement and technical controls.",
    "Un ataque a la cadena de suministro compromete un proveedor, producto, servicio o canal de actualización de confianza para alcanzar a clientes posteriores. El atacante puede alterar código fuente, sistemas de compilación, paquetes, firmware, accesos de servicios gestionados o infraestructura de distribución, obteniendo escala y confianza heredada. Son incidentes difíciles porque la actividad maliciosa puede llegar a través de un componente que ha superado los controles habituales de compra y técnicos."
  ),
  "digital-identity": l(
    "A digital identity is the collection of attributes, credentials, identifiers and relationships used to represent a person, device, workload or organisation in a system. Identity lifecycle management covers creation, proofing, changes, access assignment, monitoring and revocation. Reliable identity is foundational because every access decision depends on knowing who or what is requesting an action and under which authority.",
    "Una identidad digital es el conjunto de atributos, credenciales, identificadores y relaciones que representan a una persona, dispositivo, carga de trabajo u organización dentro de un sistema. Su ciclo de vida incluye alta, verificación, cambios, asignación de accesos, monitorización y revocación. Una identidad fiable es fundamental porque toda decisión de acceso depende de saber quién o qué solicita una acción y con qué autoridad."
  ),
  "authentication-authorisation": l(
    "Authentication establishes that an entity is the identity it claims to be; authorisation determines what that authenticated identity may do. They are separate controls: a user can be correctly authenticated yet still receive excessive access, and an authorisation rule is useless if the identity behind it can be easily impersonated. Sessions, context and policy enforcement connect both stages during actual use.",
    "La autenticación comprueba que una entidad es la identidad que afirma ser; la autorización determina qué puede hacer esa identidad ya autenticada. Son controles distintos: una persona puede autenticarse correctamente y aun así recibir permisos excesivos, y una regla de autorización no sirve si la identidad puede suplantarse con facilidad. Las sesiones, el contexto y la aplicación de políticas conectan ambas fases durante el uso real."
  ),
  "modern-authentication": l(
    "Modern authentication reduces reliance on reusable passwords by combining multiple independent factors or using phishing-resistant cryptographic credentials. Multi-factor authentication can use possession, knowledge or inherence, while passkeys and hardware-backed authenticators prove control of a private key without sending a shared secret. The strength of the system also depends on enrolment, device recovery, fallback methods and resistance to social engineering.",
    "La autenticación moderna reduce la dependencia de contraseñas reutilizables mediante varios factores independientes o credenciales criptográficas resistentes al phishing. La MFA puede combinar posesión, conocimiento o biometría, mientras que las passkeys y autenticadores respaldados por hardware demuestran el control de una clave privada sin enviar un secreto compartido. La solidez del sistema también depende del alta, la recuperación de dispositivos, los métodos alternativos y la resistencia a la ingeniería social."
  ),
  "federation-sso": l(
    "Federation allows one identity provider to make trusted assertions to another service, and single sign-on lets users access several applications after one authentication flow. Protocols such as SAML and OpenID Connect carry identity and session information between parties. This improves usability and central control, but it also concentrates risk in identity-provider configuration, signing keys, claims, application trust and session lifetime.",
    "La federación permite que un proveedor de identidad emita afirmaciones de confianza para otro servicio, y el inicio de sesión único permite acceder a varias aplicaciones tras un solo flujo de autenticación. Protocolos como SAML y OpenID Connect transportan identidad y sesión entre las partes. Esto mejora la usabilidad y el control central, pero también concentra riesgo en la configuración del proveedor, las claves de firma, los atributos, la confianza de las aplicaciones y la duración de las sesiones."
  ),
  "access-control-models": l(
    "Access-control models define how permissions are assigned and evaluated. Role-based control groups permissions by job function, attribute-based control evaluates characteristics and context, discretionary control lets owners delegate access, and mandatory control enforces centrally defined labels. Real systems often combine models, and the important design task is to make policy understandable, least-privileged and consistently enforced.",
    "Los modelos de control de acceso definen cómo se asignan y evalúan los permisos. El control basado en roles agrupa permisos por función, el basado en atributos evalúa características y contexto, el discrecional permite que los propietarios deleguen acceso y el obligatorio aplica etiquetas definidas de forma central. Los sistemas reales suelen combinar modelos; lo importante es que la política sea comprensible, de mínimo privilegio y se aplique de forma coherente."
  ),
  "privileged-access": l(
    "Privileged access grants the ability to administer systems, alter security controls, read highly sensitive data or affect many users. Privileged access management therefore separates administrative and everyday identities, stores and rotates credentials, requires stronger approval and authentication, records sessions and provides time-limited elevation. The aim is to reduce both deliberate misuse and the blast radius of a stolen administrator account.",
    "El acceso privilegiado permite administrar sistemas, modificar controles de seguridad, leer datos muy sensibles o afectar a muchos usuarios. Su gestión separa identidades administrativas y de uso diario, custodia y rota credenciales, exige autenticación y aprobación reforzadas, registra sesiones y concede elevación temporal. El objetivo es reducir tanto el abuso deliberado como el radio de impacto de una cuenta de administración robada."
  ),
  "machine-identities-secrets": l(
    "Applications, services, containers, devices and automation also need identities, often at a far greater scale than human users. They authenticate with certificates, keys, tokens and other secrets that must be issued, stored, scoped, rotated and revoked securely. Hard-coded secrets, shared service accounts and long-lived credentials create invisible trust paths that attackers can exploit without interacting with a person.",
    "Las aplicaciones, servicios, contenedores, dispositivos y automatizaciones también necesitan identidades, a menudo en una escala mucho mayor que los usuarios humanos. Se autentican mediante certificados, claves, tokens y otros secretos que deben emitirse, custodiarse, limitarse, rotarse y revocarse de forma segura. Los secretos incrustados en código, las cuentas de servicio compartidas y las credenciales de larga duración crean rutas de confianza invisibles que pueden explotarse sin interactuar con una persona."
  ),
  "network-fundamentals": l(
    "Network security begins with understanding how addressing, routing, switching, name resolution, ports, protocols and stateful connections move data between systems. The layered model helps locate where a control or failure operates, while packet flows reveal which endpoints communicate and why. Without this foundation, it is difficult to place firewalls, diagnose exposure or interpret network evidence accurately.",
    "La seguridad de redes parte de comprender cómo el direccionamiento, el enrutamiento, la conmutación, la resolución de nombres, los puertos, los protocolos y las conexiones con estado mueven datos entre sistemas. El modelo por capas ayuda a localizar dónde actúa un control o un fallo, mientras que los flujos de paquetes muestran qué extremos se comunican y por qué. Sin esta base resulta difícil ubicar firewalls, diagnosticar exposición o interpretar evidencias de red con precisión."
  ),
  "firewalls-proxies": l(
    "Firewalls decide which network connections are permitted according to source, destination, service, state and sometimes application or identity. Proxies terminate and recreate connections on behalf of clients or servers, enabling inspection, policy enforcement, content filtering and concealment of internal systems. Neither control makes unsafe applications safe, and overly broad rules can turn a carefully placed device into little more than a routing hop.",
    "Los firewalls deciden qué conexiones de red se permiten según origen, destino, servicio, estado y, en ocasiones, aplicación o identidad. Los proxies terminan y recrean conexiones en nombre de clientes o servidores, lo que permite inspección, aplicación de políticas, filtrado de contenido y ocultación de sistemas internos. Ninguno vuelve segura una aplicación insegura, y unas reglas demasiado amplias pueden convertir un control bien situado en poco más que un salto de encaminamiento."
  ),
  "segmentation": l(
    "Network segmentation divides an environment into zones with controlled communication between them. Boundaries may separate users, servers, management networks, production systems, development, guests or high-value assets, limiting lateral movement and containing faults. Effective segmentation requires an explicit traffic model, default-deny rules where feasible, protected administration and continuous verification that hidden paths have not bypassed the design.",
    "La segmentación de red divide un entorno en zonas con comunicaciones controladas entre ellas. Los límites pueden separar usuarios, servidores, redes de gestión, producción, desarrollo, invitados o activos de alto valor, reduciendo el movimiento lateral y conteniendo fallos. Una segmentación eficaz exige un modelo explícito de tráfico, reglas de denegación por defecto cuando sea viable, administración protegida y verificación continua de que no existen rutas ocultas que eludan el diseño."
  ),
  "secure-remote-access": l(
    "Remote access extends an organisation's trust boundary to users, administrators, suppliers and devices outside controlled premises. Secure designs authenticate both user and device, minimise exposed services, limit access to required resources, inspect sessions and protect administrative paths. Traditional VPN connectivity can be appropriate, but broad network-level access should not be confused with precise, context-aware authorisation.",
    "El acceso remoto amplía el límite de confianza de una organización a usuarios, administradores, proveedores y dispositivos fuera de instalaciones controladas. Los diseños seguros autentican a la persona y al dispositivo, reducen servicios expuestos, limitan el acceso a los recursos necesarios, inspeccionan sesiones y protegen las rutas administrativas. Una VPN tradicional puede ser adecuada, pero el acceso amplio a nivel de red no debe confundirse con una autorización precisa y contextual."
  ),
  "network-detection": l(
    "Network detection and response analyses packets, flows, DNS, TLS metadata and communication patterns to find suspicious activity that endpoint controls may miss. It can reveal command-and-control traffic, scanning, unusual data transfer, lateral movement and communications from unmanaged assets. Detection quality depends on sensor placement, encrypted-traffic strategy, baselines, context and an investigation process capable of validating alerts.",
    "La detección y respuesta de red analiza paquetes, flujos, DNS, metadatos TLS y patrones de comunicación para encontrar actividad sospechosa que los controles de endpoint pueden no ver. Puede revelar mando y control, escaneos, transferencias de datos anómalas, movimiento lateral y comunicaciones de activos no gestionados. La calidad depende de la ubicación de sensores, la estrategia ante tráfico cifrado, las líneas base, el contexto y un proceso de investigación capaz de validar alertas."
  ),
  "wireless-network-security": l(
    "Wireless security protects communications that travel through shared radio spectrum and therefore extend beyond physical walls. It covers strong encryption and authentication, secure configuration of access points, client isolation, rogue-device detection, guest separation and protection of management interfaces. Modern wireless environments may also include cellular, Bluetooth and mesh technologies, each with different trust and visibility constraints.",
    "La seguridad inalámbrica protege comunicaciones que viajan por un espectro radioeléctrico compartido y, por tanto, atraviesan los límites físicos. Incluye cifrado y autenticación robustos, configuración segura de puntos de acceso, aislamiento de clientes, detección de dispositivos no autorizados, separación de invitados y protección de interfaces de gestión. Los entornos modernos también pueden incluir tecnologías celulares, Bluetooth y malla, cada una con restricciones distintas de confianza y visibilidad."
  ),
  "hardening-fundamentals": l(
    "Hardening reduces the attack surface of a system by removing unnecessary functions, changing insecure defaults and enforcing a known secure configuration. It includes services, ports, accounts, permissions, software, logging, cryptography and administrative interfaces. A hardened baseline must be tested against operational needs and maintained over time, because updates, emergency changes and drift can silently reintroduce exposure.",
    "El bastionado reduce la superficie de ataque de un sistema eliminando funciones innecesarias, cambiando valores predeterminados inseguros y aplicando una configuración segura conocida. Abarca servicios, puertos, cuentas, permisos, software, registros, criptografía e interfaces administrativas. Una línea base de bastionado debe probarse frente a las necesidades operativas y mantenerse, porque las actualizaciones, cambios urgentes y desviaciones pueden reintroducir exposición de forma silenciosa."
  ),
  "patch-vulnerability-management": l(
    "Vulnerability management is the continuing process of discovering assets and weaknesses, assessing exploitability and impact, prioritising treatment, deploying remediation and confirming closure. Patching is one treatment, but others include configuration changes, isolation, compensating controls or service retirement. Priority should reflect exposure and business context, not only a severity score, and exceptions need ownership and expiry.",
    "La gestión de vulnerabilidades es el proceso continuo de descubrir activos y debilidades, evaluar explotabilidad e impacto, priorizar el tratamiento, aplicar la corrección y confirmar el cierre. El parcheado es una opción, pero también existen cambios de configuración, aislamiento, controles compensatorios o retirada del servicio. La prioridad debe reflejar exposición y contexto de negocio, no solo una puntuación de severidad, y las excepciones necesitan responsable y fecha de caducidad."
  ),
  "endpoint-hardening": l(
    "Endpoint hardening protects laptops, desktops and mobile devices that process data and interact directly with users. It combines secure configuration, application control, disk encryption, endpoint detection, restricted local administration, browser protection, device management and rapid update. Because endpoints routinely encounter untrusted content and networks, identity and recovery controls are as important as malware prevention.",
    "El bastionado de equipos protege portátiles, puestos de trabajo y dispositivos móviles que procesan datos e interactúan directamente con usuarios. Combina configuración segura, control de aplicaciones, cifrado de disco, detección en endpoint, restricción de administración local, protección del navegador, gestión del dispositivo y actualización rápida. Como estos equipos tratan contenido y redes no fiables, la identidad y la recuperación son tan importantes como la prevención de malware."
  ),
  "server-hardening": l(
    "Server hardening applies secure baselines to Windows, Linux and other server platforms according to their role. It restricts installed packages and services, protects remote administration, separates service identities, limits file and registry permissions, configures audit logs and reduces kernel or operating-system exposure. The baseline must account for workload dependencies so that security changes do not create hidden availability failures.",
    "El bastionado de servidores aplica líneas base seguras a Windows, Linux y otras plataformas según su función. Restringe paquetes y servicios instalados, protege la administración remota, separa identidades de servicio, limita permisos de ficheros y registro, configura auditoría y reduce la exposición del sistema operativo o núcleo. La línea base debe considerar las dependencias de la carga para que los cambios de seguridad no provoquen fallos ocultos de disponibilidad."
  ),
  "platform-hardening": l(
    "Platform hardening secures virtual machines, hypervisors, container runtimes and images that host workloads. It addresses image provenance, minimal base components, isolation boundaries, runtime privileges, host access, orchestration settings and management-plane exposure. Containers share more of the host than full virtual machines, so a secure image alone cannot compensate for a weak runtime or over-privileged deployment.",
    "El bastionado de plataformas protege máquinas virtuales, hipervisores, runtimes de contenedores e imágenes que alojan cargas. Abarca procedencia de imágenes, componentes base mínimos, límites de aislamiento, privilegios en ejecución, acceso al host, configuración de orquestación y exposición del plano de gestión. Los contenedores comparten más elementos del host que una máquina virtual completa, por lo que una imagen segura no compensa un runtime débil o un despliegue con privilegios excesivos."
  ),
  "configuration-management": l(
    "Configuration management defines approved states, applies them consistently and detects drift from those states. Infrastructure as code, policy as code, version control and automated compliance checks make changes traceable and repeatable. The security value comes from governing the whole change lifecycle: proposed configuration, review, deployment, exception, rollback and confirmation that the running system matches the intended state.",
    "La gestión de configuración define estados aprobados, los aplica de forma coherente y detecta desviaciones. La infraestructura como código, la política como código, el control de versiones y las comprobaciones automáticas hacen que los cambios sean trazables y repetibles. Su valor de seguridad procede de gobernar todo el ciclo: propuesta, revisión, despliegue, excepción, reversión y confirmación de que el sistema en ejecución coincide con el estado previsto."
  ),
  "cloud-fundamentals": l(
    "Cloud security applies familiar security goals to highly automated, API-driven and shared infrastructure. Resources can be created quickly, identities often control more than network position, and management planes become critical assets. Effective security therefore combines architecture, identity, logging, configuration, data protection, workload defence and resilience across infrastructure, platform and software services.",
    "La seguridad en la nube aplica objetivos conocidos a una infraestructura muy automatizada, gobernada por API y compartida. Los recursos pueden crearse con rapidez, las identidades suelen tener más peso que la posición de red y los planos de gestión se convierten en activos críticos. Por ello combina arquitectura, identidad, registros, configuración, protección de datos, defensa de cargas y resiliencia en servicios de infraestructura, plataforma y software."
  ),
  "shared-responsibility": l(
    "The shared-responsibility model divides security duties between a cloud provider and its customer, but the boundary changes by service type and contract. Providers normally protect the underlying facilities and service infrastructure, while customers remain responsible for their identities, data, configuration, workloads and use of the service. Responsibility can be delegated, but accountability for understanding the boundary cannot.",
    "El modelo de responsabilidad compartida reparte obligaciones de seguridad entre el proveedor de nube y el cliente, pero el límite cambia según el tipo de servicio y el contrato. El proveedor suele proteger instalaciones e infraestructura subyacente, mientras el cliente conserva la responsabilidad sobre identidades, datos, configuración, cargas y uso del servicio. Las tareas pueden delegarse, pero no la obligación de comprender el reparto."
  ),
  "cloud-posture-workloads": l(
    "Cloud posture management identifies risky configurations and policy violations across accounts, subscriptions and services, while workload protection observes hosts, containers and serverless functions during execution. Together they address both static exposure and active behaviour. Context is essential because a public resource, powerful identity or vulnerable workload becomes far more serious when connected to sensitive data or reachable attack paths.",
    "La gestión de postura en la nube identifica configuraciones arriesgadas e incumplimientos en cuentas, suscripciones y servicios, mientras la protección de cargas observa hosts, contenedores y funciones serverless durante la ejecución. Juntas cubren exposición estática y comportamiento activo. El contexto es esencial: un recurso público, una identidad poderosa o una carga vulnerable es mucho más grave cuando conecta con datos sensibles o rutas de ataque alcanzables."
  ),
  "containers-kubernetes": l(
    "Container and Kubernetes security spans source images, registries, build pipelines, cluster control planes, node configuration, workloads, secrets and network policy. Kubernetes continuously reconciles declared state and grants powerful automation through its API, so identity and admission controls are central. Security must prevent risky deployment while also detecting runtime behaviour that escaped preventive policy.",
    "La seguridad de contenedores y Kubernetes abarca imágenes de origen, registros, pipelines de compilación, planos de control, configuración de nodos, cargas, secretos y políticas de red. Kubernetes reconcilia continuamente el estado declarado y ofrece una automatización potente mediante su API, por lo que la identidad y los controles de admisión son centrales. La seguridad debe impedir despliegues arriesgados y detectar comportamientos en ejecución que hayan superado la prevención."
  ),
  "cloud-data-resilience": l(
    "Cloud data security controls where information is stored, who and what can access it, how it is encrypted, copied, retained and deleted, and whether recovery remains possible after compromise. Resilience requires independent backups, versioning, immutable or protected copies, tested restoration and awareness of regional and provider dependencies. Replication improves availability but is not automatically a backup because corruption or deletion may replicate too.",
    "La seguridad de datos en la nube controla dónde se almacena la información, quién o qué puede acceder, cómo se cifra, copia, conserva y elimina, y si sigue siendo recuperable tras un compromiso. La resiliencia exige copias independientes, versionado, copias inmutables o protegidas, restauración probada y conocimiento de dependencias regionales y del proveedor. La replicación mejora disponibilidad, pero no es automáticamente una copia porque también puede replicar corrupción o borrado."
  ),
  "secure-sdlc": l(
    "A secure software development lifecycle integrates security into planning, design, coding, testing, release and maintenance rather than adding a final review. It defines security requirements, threat models, coding standards, dependency controls, automated checks, review gates, vulnerability handling and ownership. The aim is to prevent classes of defect early and create evidence that released software meets an agreed level of assurance.",
    "Un ciclo de desarrollo seguro integra la seguridad en planificación, diseño, programación, pruebas, publicación y mantenimiento, en lugar de añadir una revisión final. Define requisitos, modelado de amenazas, normas de codificación, controles de dependencias, comprobaciones automáticas, puertas de revisión, gestión de vulnerabilidades y responsables. El objetivo es prevenir familias de defectos desde el principio y demostrar que el software publicado alcanza un nivel de garantía acordado."
  ),
  "application-testing": l(
    "Application security testing uses complementary techniques because no single test sees every defect. Static analysis examines code without execution, dynamic analysis tests a running application, composition analysis identifies vulnerable dependencies, interactive testing combines runtime and code context, and manual penetration testing explores logic and chained weaknesses. Results require triage and validation to distinguish exploitable risk from noise.",
    "Las pruebas de seguridad de aplicaciones combinan técnicas porque ninguna detecta todos los defectos. El análisis estático examina código sin ejecutarlo, el dinámico prueba una aplicación en marcha, el análisis de composición identifica dependencias vulnerables, las pruebas interactivas unen contexto de código y ejecución, y el pentesting manual explora lógica y cadenas de debilidades. Los resultados deben validarse para separar riesgo explotable de ruido."
  ),
  "web-security": l(
    "Web application security protects browser-facing functionality, server logic and the trust boundary between them. Major risks include injection, broken access control, cross-site scripting, request forgery, insecure deserialisation, server-side request forgery, unsafe file handling and exposure of sensitive data. Secure design relies on strict input handling, contextual output encoding, robust sessions, server-side authorisation and safe browser controls.",
    "La seguridad de aplicaciones web protege la funcionalidad expuesta al navegador, la lógica del servidor y el límite de confianza entre ambos. Entre los riesgos principales están inyección, control de acceso roto, XSS, falsificación de solicitudes, deserialización insegura, SSRF, tratamiento peligroso de ficheros y exposición de datos sensibles. El diseño seguro exige validación estricta, codificación de salida contextual, sesiones robustas, autorización en servidor y controles seguros del navegador."
  ),
  "api-session-security": l(
    "API security protects machine-to-machine interfaces that expose data and business operations, while session security protects the continuity of an authenticated interaction. Risks include weak object-level authorisation, excessive data exposure, token leakage, replay, unsafe rate limits and confused trust between services. Controls must validate every request, scope tokens narrowly, protect keys and cookies, and end sessions reliably.",
    "La seguridad de API protege interfaces máquina a máquina que exponen datos y operaciones de negocio, mientras la seguridad de sesión protege la continuidad de una interacción autenticada. Los riesgos incluyen autorización débil a nivel de objeto, exposición excesiva de datos, fuga de tokens, repetición, límites de uso inseguros y confianza confusa entre servicios. Los controles deben validar cada solicitud, limitar tokens, proteger claves y cookies, y cerrar sesiones de forma fiable."
  ),
  "software-supply-chain": l(
    "Software supply-chain security protects the components, tools and processes used to produce and distribute software. It covers source repositories, developer identities, build runners, dependencies, package registries, artefact signing, release channels and software bills of materials. Assurance comes from preserving provenance and integrity from source to deployment, not simply scanning the final package for known vulnerabilities.",
    "La seguridad de la cadena de suministro software protege componentes, herramientas y procesos usados para producir y distribuir software. Abarca repositorios de código, identidades de desarrollo, ejecutores de compilación, dependencias, registros de paquetes, firma de artefactos, canales de publicación y listas de materiales de software. La garantía procede de preservar procedencia e integridad desde el código hasta el despliegue, no solo de escanear el paquete final."
  ),
  "data-lifecycle": l(
    "Data security begins by knowing what information exists, why it is collected, how sensitive it is and where it moves throughout its lifecycle. Classification guides handling requirements for creation, storage, use, sharing, archiving and deletion. Effective controls follow the data across systems and suppliers, while minimisation reduces both privacy risk and the amount an attacker can steal.",
    "La seguridad del dato empieza por saber qué información existe, por qué se recopila, qué sensibilidad tiene y por dónde circula durante su ciclo de vida. La clasificación guía los requisitos de tratamiento en creación, almacenamiento, uso, intercambio, archivo y eliminación. Los controles eficaces acompañan al dato entre sistemas y proveedores, mientras la minimización reduce el riesgo de privacidad y la cantidad que un atacante podría robar."
  ),
  "cryptographic-protection": l(
    "Cryptographic protection uses mathematical mechanisms for confidentiality, integrity, authenticity and sometimes non-repudiation. Encryption keeps readable content from unauthorised parties, hashing creates one-way digests for integrity and password storage, and tokenisation replaces sensitive values with controlled substitutes. Security depends as much on key generation, storage, rotation and destruction as on the selected algorithm.",
    "La protección criptográfica utiliza mecanismos matemáticos para aportar confidencialidad, integridad, autenticidad y, en algunos casos, no repudio. El cifrado impide que terceros no autorizados lean el contenido, el hashing crea resúmenes unidireccionales para integridad y almacenamiento de contraseñas, y la tokenización sustituye valores sensibles por referencias controladas. La seguridad depende tanto de generar, custodiar, rotar y destruir claves como del algoritmo elegido."
  ),
  "pki-certificates": l(
    "Public key infrastructure binds public keys to identities through certificates and a chain of trust. Certificate authorities issue and revoke certificates, relying parties validate names, dates, signatures and revocation status, and private keys prove control. PKI supports TLS, code signing, document signatures and device identity, but expired certificates, weak issuance or stolen private keys can undermine the entire trust decision.",
    "La infraestructura de clave pública vincula claves públicas con identidades mediante certificados y una cadena de confianza. Las autoridades certificadoras emiten y revocan certificados, las partes confiantes validan nombres, fechas, firmas y revocación, y las claves privadas demuestran control. La PKI sustenta TLS, firma de código, firma documental e identidad de dispositivos, pero un certificado caducado, una emisión débil o una clave privada robada pueden invalidar toda la confianza."
  ),
  "data-loss-prevention": l(
    "Data loss prevention identifies sensitive information and applies policy when it is stored, used or transmitted. It can inspect endpoints, email, web traffic, cloud services and repositories to warn, block, quarantine, encrypt or record risky actions. DLP is most effective when classification and business process are understood; otherwise it produces false positives or merely displaces data movement to an unmonitored channel.",
    "La prevención de pérdida de datos identifica información sensible y aplica políticas cuando se almacena, usa o transmite. Puede inspeccionar endpoints, correo, tráfico web, servicios en la nube y repositorios para avisar, bloquear, poner en cuarentena, cifrar o registrar acciones arriesgadas. Es más eficaz cuando se comprenden la clasificación y el proceso de negocio; de lo contrario genera falsos positivos o desplaza el movimiento de datos a un canal no monitorizado."
  ),
  "critical-infrastructure": l(
    "Critical-infrastructure cybersecurity protects systems whose disruption could seriously affect public safety, essential services, the economy or national security. These environments combine information technology, operational technology, telecommunications, physical equipment and multiple organisations. Decisions must account for safety, long asset lifecycles, limited maintenance windows and consequences that can extend far beyond the owner of the compromised system.",
    "La ciberseguridad de infraestructuras críticas protege sistemas cuya interrupción podría afectar gravemente a la seguridad pública, los servicios esenciales, la economía o la seguridad nacional. Estos entornos combinan TI, tecnología operacional, telecomunicaciones, equipos físicos y varias organizaciones. Las decisiones deben considerar seguridad física, ciclos de vida largos, ventanas de mantenimiento limitadas y consecuencias que pueden superar ampliamente al propietario del sistema comprometido."
  ),
  "essential-sectors": l(
    "Essential sectors include services such as energy, water, transport, health, finance, communications and public administration, although legal definitions vary by jurisdiction. Each sector has distinct operational processes, dependencies and tolerance for interruption. Sector security therefore requires common cyber practices to be adapted to real service delivery, safety obligations, regulation and the technologies used in that domain.",
    "Los sectores esenciales incluyen servicios como energía, agua, transporte, sanidad, finanzas, comunicaciones y administración pública, aunque la definición legal varía según la jurisdicción. Cada sector tiene procesos operativos, dependencias y tolerancia a la interrupción distintos. Por ello, las prácticas comunes de ciberseguridad deben adaptarse a la prestación real del servicio, las obligaciones de seguridad, la regulación y las tecnologías propias de cada ámbito."
  ),
  "cascading-failures": l(
    "A cascading failure occurs when disruption in one system propagates through technical, organisational or physical dependencies and causes further failures elsewhere. Shared identity, power, communications, timing, cloud or supplier services can create hidden concentration. Mapping dependencies, operating thresholds and recovery order helps identify where redundancy is only apparent and where one incident could become a cross-sector crisis.",
    "Un fallo en cascada se produce cuando la interrupción de un sistema se propaga por dependencias técnicas, organizativas o físicas y provoca nuevos fallos. Servicios compartidos de identidad, energía, comunicaciones, sincronización, nube o proveedores pueden crear concentraciones ocultas. Representar dependencias, umbrales operativos y orden de recuperación ayuda a detectar dónde la redundancia es solo aparente y dónde un incidente podría convertirse en una crisis intersectorial."
  ),
  "critical-resilience": l(
    "Critical resilience is the ability of an essential service to anticipate disruption, absorb it, continue at an acceptable level, recover and adapt. It combines prevention with redundancy, manual workarounds, spares, crisis governance, mutual assistance and tested recovery. The central measure is not whether every component remains available, but whether the vital outcome can still be delivered safely.",
    "La resiliencia crítica es la capacidad de un servicio esencial para anticipar una interrupción, absorberla, continuar a un nivel aceptable, recuperarse y adaptarse. Combina prevención con redundancia, alternativas manuales, repuestos, gobierno de crisis, ayuda mutua y recuperación probada. La medida central no es que todos los componentes sigan disponibles, sino que el resultado vital pueda prestarse de forma segura."
  ),
  "ot-ics": l(
    "Operational technology and industrial control systems monitor or control physical processes such as production, power, water, transport and building operations. Controllers, sensors, actuators, safety systems and supervisory platforms interact with real equipment, so cyber actions can have physical and safety consequences. Availability, deterministic behaviour and engineering constraints often shape security decisions more strongly than in ordinary office IT.",
    "La tecnología operacional y los sistemas de control industrial supervisan o controlan procesos físicos como producción, energía, agua, transporte y edificios. Controladores, sensores, actuadores, sistemas de seguridad y plataformas de supervisión interactúan con equipos reales, por lo que una acción cibernética puede producir consecuencias físicas y de seguridad. La disponibilidad, el comportamiento determinista y las restricciones de ingeniería suelen condicionar más las decisiones que en la TI de oficina."
  ),
  "ot-architecture": l(
    "A secure OT architecture separates business, supervisory, control and safety functions while allowing only required and monitored data flows. Industrial demilitarised zones, jump hosts, unidirectional gateways and controlled remote access reduce direct paths to critical control. Architecture must reflect the actual process, fail-safe behaviour and maintenance needs rather than copying an IT network pattern without engineering analysis.",
    "Una arquitectura OT segura separa funciones de negocio, supervisión, control y seguridad, permitiendo solo los flujos de datos necesarios y monitorizados. Las zonas desmilitarizadas industriales, hosts de salto, pasarelas unidireccionales y acceso remoto controlado reducen rutas directas hacia el control crítico. La arquitectura debe reflejar el proceso real, el comportamiento seguro ante fallo y las necesidades de mantenimiento, no copiar un patrón de red TI sin análisis de ingeniería."
  ),
  "ot-monitoring-assets": l(
    "OT asset inventory identifies controllers, workstations, network devices, firmware, protocols, owners and process roles without disrupting sensitive operations. Passive monitoring learns from existing traffic and is often preferred where active scanning could affect legacy devices or deterministic processes. The resulting context allows defenders to distinguish normal industrial communication from new assets, unsafe changes or suspicious commands.",
    "El inventario de activos OT identifica controladores, estaciones, dispositivos de red, firmware, protocolos, responsables y funciones de proceso sin alterar operaciones sensibles. La monitorización pasiva aprende del tráfico existente y suele preferirse cuando un escaneo activo podría afectar a equipos heredados o procesos deterministas. Ese contexto permite distinguir comunicaciones industriales normales de activos nuevos, cambios inseguros o comandos sospechosos."
  ),
  "ot-remote-vendor-access": l(
    "Remote and vendor access is often necessary to maintain specialised industrial equipment, but it can create a direct route into high-consequence systems. Secure access uses named identities, strong authentication, approval, time limits, monitored jump infrastructure, least privilege and rapid revocation. Persistent shared accounts or unmanaged vendor modems bypass both accountability and architectural controls.",
    "El acceso remoto y de proveedores suele ser necesario para mantener equipos industriales especializados, pero puede crear una ruta directa a sistemas de grandes consecuencias. El acceso seguro usa identidades nominales, autenticación robusta, aprobación, límites temporales, infraestructura de salto monitorizada, mínimo privilegio y revocación rápida. Las cuentas compartidas permanentes o módems de proveedor no gestionados eluden la trazabilidad y los controles arquitectónicos."
  ),
  "ot-incident-recovery": l(
    "OT incident response must coordinate cyber investigation with process safety, engineering authority and physical operations. Containment actions that are routine in IT, such as isolating or rebooting a host, may stop production or create unsafe states. Recovery therefore relies on validated configurations, offline engineering records, tested spares, manual operation where possible and a carefully sequenced return to service.",
    "La respuesta a incidentes OT debe coordinar la investigación cibernética con seguridad del proceso, autoridad de ingeniería y operación física. Acciones habituales en TI, como aislar o reiniciar un equipo, pueden detener la producción o crear estados inseguros. La recuperación depende de configuraciones validadas, documentación de ingeniería fuera de línea, repuestos probados, operación manual cuando sea posible y una vuelta al servicio cuidadosamente secuenciada."
  ),
  "incident-response": l(
    "Incident response is the organised capability to prepare for, detect, analyse, contain, eradicate and recover from security incidents. It defines decision authority, technical playbooks, evidence handling, communications, legal coordination and lessons learned. The phases are iterative rather than strictly linear: new evidence can change scope, require additional containment or reveal that recovery is not yet trustworthy.",
    "La respuesta a incidentes es la capacidad organizada para prepararse, detectar, analizar, contener, erradicar y recuperarse de incidentes de seguridad. Define autoridad de decisión, procedimientos técnicos, tratamiento de evidencias, comunicaciones, coordinación legal y lecciones aprendidas. Las fases son iterativas, no estrictamente lineales: una nueva evidencia puede cambiar el alcance, exigir más contención o demostrar que la recuperación aún no es fiable."
  ),
  "containment-recovery": l(
    "Containment limits the spread and impact of an active incident while preserving enough evidence and service continuity to support investigation. Eradication removes attacker access, persistence and root cause; recovery restores systems from a known-good state and monitors for recurrence. Speed matters, but premature restoration with compromised identities or backups can restart the incident.",
    "La contención limita la propagación y el impacto de un incidente activo conservando evidencia y suficiente continuidad para investigar. La erradicación elimina el acceso atacante, la persistencia y la causa raíz; la recuperación restaura sistemas desde un estado fiable y vigila posibles reapariciones. La rapidez importa, pero restaurar antes de limpiar identidades o validar copias puede reiniciar el incidente."
  ),
  "incident-communication": l(
    "Incident and crisis communication ensures that technical facts become timely decisions for employees, leaders, customers, regulators, partners and the public. Messages must distinguish confirmed evidence from assumptions, protect sensitive investigation details and remain consistent across channels. Good communication assigns approval authority, keeps a decision log and adapts content to each audience without creating false certainty.",
    "La comunicación de incidentes y crisis convierte hechos técnicos en decisiones oportunas para empleados, dirección, clientes, reguladores, socios y público. Los mensajes deben separar evidencias confirmadas de supuestos, proteger detalles sensibles de la investigación y mantener coherencia entre canales. Una buena comunicación asigna autoridad de aprobación, conserva un registro de decisiones y adapta el contenido a cada audiencia sin crear falsas certezas."
  ),
  "digital-forensics": l(
    "Digital forensics is the disciplined identification, collection, preservation, examination and interpretation of digital evidence. It seeks to reconstruct what happened, when, how and with what scope while maintaining integrity and a defensible chain of custody. Forensic work may support incident response, legal proceedings, internal investigations or intelligence, and conclusions must reflect the limits of the available evidence.",
    "La informática forense es la identificación, adquisición, preservación, examen e interpretación disciplinados de evidencias digitales. Busca reconstruir qué ocurrió, cuándo, cómo y con qué alcance, manteniendo integridad y una cadena de custodia defendible. Puede apoyar respuesta a incidentes, procedimientos legales, investigaciones internas o inteligencia, y sus conclusiones deben reflejar los límites de la evidencia disponible."
  ),
  "forensic-sources": l(
    "Forensic sources include volatile memory, disks, endpoint telemetry, event logs, network records, cloud audit trails, identity systems, email and application data. Each source has different retention, reliability, clock behaviour and collection risk. Building a timeline requires normalising timestamps, correlating identifiers and recognising that absence of a log entry is not always proof that an action did not occur.",
    "Las fuentes forenses incluyen memoria volátil, discos, telemetría de endpoint, registros de eventos, datos de red, auditoría de nube, sistemas de identidad, correo y aplicaciones. Cada fuente tiene retención, fiabilidad, reloj y riesgo de adquisición distintos. Construir una línea temporal exige normalizar marcas de tiempo, correlacionar identificadores y entender que la ausencia de un registro no siempre demuestra que una acción no ocurrió."
  ),
  "security-operations": l(
    "A security operations centre coordinates continuous monitoring, alert triage, investigation, response and improvement across people, process and technology. It brings together telemetry, detection rules, case management, threat intelligence and operational playbooks. Its effectiveness is measured by the quality and timeliness of decisions, not by alert volume or the number of tools displayed on a screen.",
    "Un centro de operaciones de seguridad coordina monitorización continua, triaje de alertas, investigación, respuesta y mejora entre personas, procesos y tecnología. Integra telemetría, reglas de detección, gestión de casos, inteligencia de amenazas y procedimientos operativos. Su eficacia se mide por la calidad y oportunidad de las decisiones, no por el volumen de alertas ni por el número de herramientas mostradas en una pantalla."
  ),
  "detection-engineering": l(
    "Detection engineering designs, tests, deploys and maintains analytical logic that identifies harmful behaviour from available telemetry. A good detection has a clear threat hypothesis, required data, expected false positives, severity, investigation guidance and validation evidence. Rules must evolve as systems and adversaries change, and coverage should be mapped to important attack behaviours rather than accumulated without purpose.",
    "La ingeniería de detección diseña, prueba, despliega y mantiene lógica analítica que identifica comportamientos dañinos a partir de la telemetría disponible. Una buena detección tiene una hipótesis de amenaza clara, datos necesarios, falsos positivos esperados, severidad, guía de investigación y evidencia de validación. Las reglas deben evolucionar con sistemas y adversarios, y la cobertura debe relacionarse con comportamientos de ataque relevantes."
  ),
  "threat-hunting-intelligence": l(
    "Threat intelligence collects and analyses information about adversaries, campaigns, vulnerabilities and context to support decisions; threat hunting proactively searches an environment for evidence that existing detections have missed. Hunting begins with a testable hypothesis and ends with findings, improved telemetry or new detections. Indicators are useful, but behaviours and environmental context usually remain valuable for longer.",
    "La inteligencia de amenazas recopila y analiza información sobre adversarios, campañas, vulnerabilidades y contexto para apoyar decisiones; la búsqueda de amenazas explora de forma proactiva el entorno en busca de evidencias que las detecciones existentes no han encontrado. Una búsqueda parte de una hipótesis verificable y termina con hallazgos, mejor telemetría o nuevas detecciones. Los indicadores ayudan, pero los comportamientos y el contexto suelen conservar valor durante más tiempo."
  ),
  "governance-risk-compliance": l(
    "Security governance sets direction, decision rights, accountability and oversight; risk management prioritises uncertainty against objectives; compliance demonstrates that defined obligations are met. These disciplines overlap but are not interchangeable. A compliant organisation can still be insecure if controls are poorly chosen or ineffective, while strong governance ensures that exceptions, investment and residual risk receive explicit ownership.",
    "El gobierno de seguridad fija dirección, derechos de decisión, responsabilidad y supervisión; la gestión de riesgos prioriza incertidumbre frente a objetivos; y el cumplimiento demuestra que se satisfacen obligaciones definidas. Se solapan, pero no son equivalentes. Una organización puede cumplir y seguir siendo insegura si los controles están mal elegidos o no funcionan, mientras un buen gobierno asigna responsable explícito a excepciones, inversión y riesgo residual."
  ),
  "risk-treatment": l(
    "Risk treatment selects how to change or accept a risk after it has been assessed. Options include avoiding the activity, reducing likelihood or impact through controls, transferring part of the consequence through contracts or insurance, and accepting residual risk with informed authority. A treatment plan needs actions, owners, dates, resources, success measures and a review trigger when assumptions change.",
    "El tratamiento del riesgo decide cómo modificar o aceptar un riesgo después de evaluarlo. Las opciones incluyen evitar la actividad, reducir probabilidad o impacto mediante controles, transferir parte de la consecuencia con contratos o seguros, y aceptar el riesgo residual con autoridad informada. Un plan necesita acciones, responsables, fechas, recursos, medidas de éxito y un desencadenante de revisión cuando cambien los supuestos."
  ),
  "frameworks-standards": l(
    "Security frameworks organise outcomes and practices, while standards specify requirements or implementation criteria in greater detail. They provide a common language for assessment, improvement and assurance, but they must be tailored to the organisation's objectives, threats and operating model. Mapping several frameworks can reduce duplication, whereas blindly implementing every control can waste effort without reducing material risk.",
    "Los marcos de seguridad organizan resultados y prácticas, mientras las normas especifican requisitos o criterios de implantación con mayor detalle. Aportan un lenguaje común para evaluación, mejora y garantía, pero deben adaptarse a objetivos, amenazas y modelo operativo. Relacionar varios marcos puede evitar duplicidades; implantar ciegamente todos los controles puede consumir recursos sin reducir riesgos relevantes."
  ),
  "third-party-risk": l(
    "Third-party risk arises when suppliers, partners and service providers can affect an organisation's data, systems or critical outcomes. Assessment covers access, concentration, subcontractors, service resilience, incident notification, data handling and exit arrangements, not just a questionnaire. Contractual promises matter only when supported by technical boundaries, monitoring, evidence and a practical response if the supplier fails.",
    "El riesgo de terceros aparece cuando proveedores, socios y prestadores pueden afectar a datos, sistemas o resultados críticos de una organización. La evaluación cubre accesos, concentración, subcontratación, resiliencia del servicio, notificación de incidentes, tratamiento de datos y salida, no solo un cuestionario. Las promesas contractuales solo sirven si se apoyan en límites técnicos, monitorización, evidencias y una respuesta práctica ante el fallo del proveedor."
  ),
  "privacy-fundamentals": l(
    "Privacy concerns the appropriate and lawful handling of information about people, including collection, purpose, use, sharing, retention and individual rights. It is related to security but broader: perfectly encrypted data can still be processed unfairly or for an unjustified purpose. Core principles include transparency, purpose limitation, minimisation, accuracy, storage limitation and accountability.",
    "La privacidad trata del uso adecuado y lícito de información sobre personas, incluida su recopilación, finalidad, utilización, cesión, conservación y derechos individuales. Está relacionada con la seguridad, pero es más amplia: unos datos perfectamente cifrados pueden tratarse de forma injusta o para una finalidad no justificada. Sus principios incluyen transparencia, limitación de finalidad, minimización, exactitud, limitación de conservación y responsabilidad proactiva."
  ),
  "privacy-engineering": l(
    "Privacy engineering turns privacy principles and legal duties into technical and operational design decisions. It uses data-flow mapping, minimisation, separation, access control, retention automation, consent and preference handling, de-identification and privacy-preserving defaults. The goal is to reduce unnecessary personal-data exposure by design rather than relying only on notices or user behaviour after deployment.",
    "La ingeniería de privacidad convierte principios y obligaciones legales en decisiones técnicas y operativas de diseño. Utiliza mapas de flujo de datos, minimización, separación, control de acceso, automatización de conservación, gestión de consentimiento y preferencias, desidentificación y valores predeterminados protectores. El objetivo es reducir por diseño la exposición innecesaria de datos personales, no depender solo de avisos o del comportamiento del usuario tras el despliegue."
  ),
  "cyber-resilience": l(
    "Cyber resilience is the ability to continue delivering important outcomes despite cyber disruption and to recover in a controlled way. It joins security, reliability, continuity, crisis management and organisational learning. Resilient design assumes that some controls will fail, so it limits blast radius, protects recovery mechanisms, defines minimum viable service and rehearses decisions under degraded conditions.",
    "La ciberresiliencia es la capacidad de seguir ofreciendo resultados importantes pese a una interrupción cibernética y recuperarse de forma controlada. Une seguridad, fiabilidad, continuidad, gestión de crisis y aprendizaje organizativo. Un diseño resiliente asume que algunos controles fallarán, por lo que limita el radio de impacto, protege mecanismos de recuperación, define un servicio mínimo viable y ensaya decisiones en condiciones degradadas."
  ),
  "backup-disaster-recovery": l(
    "Backups preserve recoverable copies of data and configuration, while disaster recovery restores technology services after major disruption. A robust strategy defines recovery point and time objectives, separates copies from production identities, protects them from alteration and regularly tests full restoration. A backup that cannot be located, decrypted or restored within the required time is not an effective recovery control.",
    "Las copias preservan versiones recuperables de datos y configuración, mientras la recuperación ante desastres restablece servicios tecnológicos tras una interrupción grave. Una estrategia sólida define objetivos de punto y tiempo de recuperación, separa copias de las identidades de producción, las protege frente a alteración y prueba restauraciones completas. Una copia que no puede localizarse, descifrarse o restaurarse a tiempo no es un control eficaz."
  ),
  "business-continuity": l(
    "Business continuity plans how critical activities will operate during and after disruption, including loss of technology, premises, people, suppliers or utilities. Business impact analysis identifies priority services, maximum tolerable downtime, dependencies and minimum resources. Continuity solutions may include alternate processes, locations, communication, staffing and manual workarounds, with technology recovery as one component rather than the entire plan.",
    "La continuidad de negocio planifica cómo funcionarán las actividades críticas durante y después de una interrupción, incluida la pérdida de tecnología, instalaciones, personal, proveedores o suministros. El análisis de impacto identifica servicios prioritarios, tiempo máximo tolerable, dependencias y recursos mínimos. Las soluciones pueden incluir procesos alternativos, ubicaciones, comunicación, personal y procedimientos manuales; la recuperación tecnológica es solo una parte del plan."
  ),
  "ai-security": l(
    "AI system security protects the complete system around a model: training and retrieval data, model artefacts, prompts, applications, tools, identities, infrastructure, suppliers and human oversight. Risks include prompt injection, unsafe tool use, data poisoning, model theft, sensitive-data leakage and manipulated outputs. Because model behaviour is probabilistic, security combines conventional controls with input isolation, constrained authority, evaluation, monitoring and human review for consequential actions.",
    "La seguridad de sistemas de IA protege el sistema completo que rodea al modelo: datos de entrenamiento y recuperación, artefactos del modelo, instrucciones, aplicaciones, herramientas, identidades, infraestructura, proveedores y supervisión humana. Los riesgos incluyen inyección de instrucciones, uso inseguro de herramientas, envenenamiento de datos, robo de modelos, fuga de información y salidas manipuladas. Como el comportamiento es probabilístico, se combinan controles convencionales con aislamiento de entradas, autoridad limitada, evaluación, monitorización y revisión humana en acciones relevantes."
  ),
  "post-quantum": l(
    "Post-quantum cryptography uses algorithms intended to resist attacks by both classical and sufficiently capable quantum computers. Migration is not only an algorithm replacement: organisations must discover where cryptography is embedded, understand data confidentiality lifetimes, update protocols and hardware, manage interoperability and test performance. Crypto-agility allows algorithms and keys to change without redesigning every dependent system.",
    "La criptografía poscuántica utiliza algoritmos concebidos para resistir ataques de ordenadores clásicos y de futuros ordenadores cuánticos con capacidad suficiente. La migración no consiste solo en sustituir un algoritmo: hay que descubrir dónde está integrada la criptografía, conocer la vida de confidencialidad de los datos, actualizar protocolos y hardware, gestionar interoperabilidad y probar rendimiento. La criptoagilidad permite cambiar algoritmos y claves sin rediseñar cada sistema dependiente."
  ),
  "iot-edge": l(
    "IoT and edge security covers large populations of connected sensors, actuators, gateways and embedded devices that often have limited resources and long lifecycles. These systems may process data or make decisions close to the physical environment, sometimes without constant cloud connectivity. Security depends on unique identity, secure boot and update, minimal services, segmentation, inventory and a supported end-of-life path.",
    "La seguridad de IoT y computación en el borde abarca grandes poblaciones de sensores, actuadores, pasarelas y dispositivos embebidos conectados, a menudo con recursos limitados y ciclos de vida largos. Pueden procesar datos o tomar decisiones cerca del entorno físico, incluso sin conexión constante a la nube. La seguridad depende de identidad única, arranque y actualización seguros, servicios mínimos, segmentación, inventario y un fin de vida con soporte definido."
  ),
  "space-5g-digital-twins": l(
    "Space systems, 5G networks and digital twins are different technologies, but all combine distributed infrastructure, complex suppliers and data-driven control of consequential services. Satellite links depend on ground segments and timing, 5G separates multiple virtualised control and user planes, and digital twins depend on accurate models and trustworthy sensor data. Security must protect management interfaces, supply chains, integrity, availability and safe interaction with physical assets.",
    "Los sistemas espaciales, las redes 5G y los gemelos digitales son tecnologías distintas, pero combinan infraestructura distribuida, proveedores complejos y control basado en datos de servicios relevantes. Los enlaces satelitales dependen de segmentos terrestres y sincronización; 5G separa varios planos virtualizados de control y usuario; y los gemelos digitales dependen de modelos precisos y datos fiables de sensores. La seguridad debe proteger interfaces de gestión, cadena de suministro, integridad, disponibilidad e interacción segura con activos físicos."
  )
};
