import type { ComparisonTable, DefensiveChecklist, Diagram } from "../types/content";

const l = (en: string, es: string) => ({ en, es });
const diagram = (id: string, en: string, es: string, labels: [string, string, string, string][], captionEn: string, captionEs: string): Diagram => ({
  id, title: l(en, es), description: l("How the main elements of this topic relate.", "Cómo se relacionan los elementos principales de este tema."),
  nodes: labels.map(([nodeEn, nodeEs, detailEn, detailEs], index) => ({ id: `${id}-${index}`, label: l(nodeEn, nodeEs), detail: l(detailEn, detailEs), tone: (["green", "blue", "amber", "red"] as const)[index % 4] })), caption: l(captionEn, captionEs)
});

export const diagrams: Diagram[] = [
  diagram("risk-chain", "From asset to risk", "Del activo al riesgo", [["Asset", "Activo", "Something valuable", "Algo valioso"], ["Threat", "Amenaza", "Potential cause of harm", "Causa potencial de daño"], ["Vulnerability", "Vulnerabilidad", "Weakness that can be exposed", "Debilidad que puede quedar expuesta"], ["Risk", "Riesgo", "Likelihood and impact", "Probabilidad e impacto"]], "Controls alter likelihood or impact; they do not make risk disappear.", "Los controles modifican la probabilidad o el impacto; no hacen desaparecer el riesgo."),
  diagram("cia", "CIA security objectives", "Objetivos de seguridad CIA", [["Confidentiality", "Confidencialidad", "Only authorised access", "Solo acceso autorizado"], ["Integrity", "Integridad", "Accurate and trustworthy", "Exacto y fiable"], ["Availability", "Disponibilidad", "Usable when needed", "Utilizable cuando se necesita"], ["Context", "Contexto", "Balance depends on mission", "El equilibrio depende de la misión"]], "Security decisions balance all three objectives in their operational context.", "Las decisiones de seguridad equilibran los tres objetivos según su contexto operativo."),
  diagram("defence-depth", "Defence in depth", "Defensa en profundidad", [["Governance", "Gobierno", "Direction and accountability", "Dirección y responsabilidad"], ["Identity", "Identidad", "Verify every access", "Verificar cada acceso"], ["Workload", "Carga", "Harden and monitor", "Bastionar y monitorizar"], ["Recovery", "Recuperación", "Restore dependable service", "Restaurar un servicio fiable"]], "Independent layers reduce reliance on any single safeguard.", "Las capas independientes reducen la dependencia de una única salvaguarda."),
  diagram("identity-flow", "Identity decision flow", "Flujo de decisión de identidad", [["Identity provider", "Proveedor de identidad", "Verifies the principal", "Verifica al principal"], ["Policy", "Política", "Evaluates context and risk", "Evalúa contexto y riesgo"], ["Application", "Aplicación", "Enforces the decision", "Aplica la decisión"], ["Audit", "Auditoría", "Records accountable activity", "Registra la actividad atribuible"]], "Authentication starts the decision; authorisation determines permitted action.", "La autenticación inicia la decisión; la autorización determina la acción permitida."),
  diagram("network-zones", "Segmented network", "Red segmentada", [["External", "Exterior", "Untrusted connectivity", "Conectividad no fiable"], ["DMZ", "DMZ", "Brokered public services", "Servicios públicos intermediados"], ["Enterprise", "Empresa", "Business systems", "Sistemas de negocio"], ["Restricted", "Restringida", "Sensitive assets", "Activos sensibles"]], "Traffic crosses explicit trust boundaries with policy and monitoring.", "El tráfico cruza límites de confianza explícitos con políticas y monitorización."),
  diagram("hardening-loop", "Hardening lifecycle", "Ciclo de bastionado", [["Baseline", "Línea base", "Define secure state", "Definir el estado seguro"], ["Deploy", "Desplegar", "Apply controlled configuration", "Aplicar configuración controlada"], ["Measure", "Medir", "Detect drift and exposure", "Detectar desviaciones y exposición"], ["Improve", "Mejorar", "Patch and refine", "Parchear y perfeccionar"]], "Hardening is maintained continuously; it is not a one-time build task.", "El bastionado se mantiene de forma continua; no es una tarea puntual."),
  diagram("shared-responsibility", "Cloud shared responsibility", "Responsabilidad compartida en la nube", [["Provider", "Proveedor", "Physical platform and managed service", "Plataforma física y servicio gestionado"], ["Customer", "Cliente", "Data, identities and configuration", "Datos, identidades y configuración"], ["Service model", "Modelo de servicio", "Boundary changes with IaaS/PaaS/SaaS", "El límite cambia con IaaS/PaaS/SaaS"], ["Assurance", "Aseguramiento", "Verify both sides", "Verificar ambas partes"]], "Responsibility is shared but never assumed; exact boundaries depend on the service contract.", "La responsabilidad se comparte, pero no se presupone; los límites exactos dependen del contrato."),
  diagram("secure-sdlc", "Secure development lifecycle", "Ciclo de desarrollo seguro", [["Design", "Diseño", "Model threats", "Modelar amenazas"], ["Build", "Construcción", "Review code and dependencies", "Revisar código y dependencias"], ["Verify", "Verificación", "Test controls and misuse", "Probar controles y uso indebido"], ["Operate", "Operación", "Monitor, learn and patch", "Monitorizar, aprender y parchear"]], "Security evidence is produced throughout delivery, not added at release.", "La evidencia de seguridad se produce durante toda la entrega, no se añade al publicar."),
  diagram("data-lifecycle", "Data protection lifecycle", "Ciclo de protección del dato", [["Create", "Crear", "Classify at source", "Clasificar en origen"], ["Use", "Usar", "Restrict and monitor", "Restringir y monitorizar"], ["Share", "Compartir", "Protect transfer and purpose", "Proteger transferencia y finalidad"], ["Dispose", "Eliminar", "Retain then erase securely", "Conservar y después borrar con seguridad"]], "Protection follows data across systems, owners and states.", "La protección acompaña al dato entre sistemas, responsables y estados."),
  diagram("critical-dependencies", "Essential-service dependencies", "Dependencias de servicios esenciales", [["Energy", "Energía", "Powers operations", "Alimenta las operaciones"], ["Telecoms", "Telecomunicaciones", "Carries coordination", "Transporta la coordinación"], ["Water", "Agua", "Supports people and industry", "Sostiene a población e industria"], ["Public services", "Servicios públicos", "Coordinate response", "Coordinan la respuesta"]], "Resilience planning must consider cascading effects across sectors.", "La planificación de resiliencia debe considerar efectos en cascada entre sectores."),
  diagram("purdue", "Conceptual industrial zones", "Zonas industriales conceptuales", [["Enterprise", "Empresa", "Business planning", "Planificación de negocio"], ["Industrial DMZ", "DMZ industrial", "Brokered exchange", "Intercambio intermediado"], ["Operations", "Operaciones", "Supervision and control", "Supervisión y control"], ["Process", "Proceso", "Physical sensing and action", "Medición y actuación física"]], "The model supports discussion; real architectures require asset-specific engineering.", "El modelo facilita el debate; las arquitecturas reales requieren ingeniería específica de activos."),
  diagram("ir-lifecycle", "Incident response lifecycle", "Ciclo de respuesta a incidentes", [["Prepare", "Preparar", "People, plans and visibility", "Personas, planes y visibilidad"], ["Detect & analyse", "Detectar y analizar", "Establish facts", "Establecer hechos"], ["Contain & recover", "Contener y recuperar", "Limit harm and restore", "Limitar el daño y restaurar"], ["Learn", "Aprender", "Improve the system", "Mejorar el sistema"]], "Communication and evidence preservation span every phase.", "La comunicación y la preservación de evidencias abarcan todas las fases."),
  diagram("forensic-chain", "Evidence chain", "Cadena de evidencia", [["Identify", "Identificar", "Locate relevant sources", "Localizar fuentes relevantes"], ["Preserve", "Preservar", "Prevent avoidable change", "Evitar cambios innecesarios"], ["Analyse", "Analizar", "Use repeatable methods", "Usar métodos repetibles"], ["Report", "Informar", "State facts and limits", "Exponer hechos y límites"]], "A documented chain of custody supports trust in the evidence.", "Una cadena de custodia documentada respalda la confianza en la evidencia."),
  diagram("soc-flow", "Security operations telemetry", "Telemetría de operaciones de seguridad", [["Sources", "Fuentes", "Identity, endpoint, network, cloud", "Identidad, equipos, red y nube"], ["Collection", "Recogida", "Normalise and enrich", "Normalizar y enriquecer"], ["Detection", "Detección", "Rules, analytics and context", "Reglas, analítica y contexto"], ["Response", "Respuesta", "Triage and coordinated action", "Triaje y acción coordinada"]], "Investigation findings improve data quality and detection logic.", "Los hallazgos de las investigaciones mejoran la calidad de los datos y la lógica de detección."),
  diagram("risk-treatment", "Risk treatment decisions", "Decisiones de tratamiento del riesgo", [["Avoid", "Evitar", "Stop the risky activity", "Detener la actividad arriesgada"], ["Mitigate", "Mitigar", "Reduce likelihood or impact", "Reducir probabilidad o impacto"], ["Transfer", "Transferir", "Share financial consequence", "Compartir la consecuencia económica"], ["Accept", "Aceptar", "Own within authority", "Asumir dentro de la autoridad"]], "Treatment selection follows risk appetite, evidence and accountable approval.", "El tratamiento sigue el apetito de riesgo, la evidencia y una aprobación responsable."),
  diagram("privacy-design", "Privacy by design", "Privacidad desde el diseño", [["Purpose", "Finalidad", "Define legitimate need", "Definir necesidad legítima"], ["Minimise", "Minimizar", "Use only necessary data", "Usar solo datos necesarios"], ["Protect", "Proteger", "Apply lifecycle controls", "Aplicar controles de ciclo de vida"], ["Explain", "Explicar", "Be transparent and accountable", "Ser transparente y responsable"]], "Privacy decisions precede collection and continue through deletion.", "Las decisiones de privacidad preceden la recogida y continúan hasta el borrado."),
  diagram("resilience", "Operational resilience", "Resiliencia operativa", [["Anticipate", "Anticipar", "Understand dependencies", "Comprender dependencias"], ["Withstand", "Resistir", "Keep critical service", "Mantener el servicio crítico"], ["Recover", "Recuperar", "Restore safely", "Restaurar con seguridad"], ["Adapt", "Adaptar", "Learn and redesign", "Aprender y rediseñar"]], "Resilience is the ability to sustain outcomes, not merely to own backups.", "La resiliencia es la capacidad de mantener resultados, no solo de tener copias."),
  diagram("ai-system", "AI system security", "Seguridad de sistemas de IA", [["Data", "Datos", "Quality and provenance", "Calidad y procedencia"], ["Model", "Modelo", "Behaviour and supply chain", "Comportamiento y cadena de suministro"], ["Application", "Aplicación", "Access and tool boundaries", "Acceso y límites de herramientas"], ["Oversight", "Supervisión", "Monitoring and human review", "Monitorización y revisión humana"]], "Security covers the whole sociotechnical system, not only the model file.", "La seguridad abarca todo el sistema sociotécnico, no solo el fichero del modelo."),
  diagram("zero-trust", "Zero Trust decision", "Decisión Zero Trust", [["Subject", "Sujeto", "Human or workload identity", "Identidad humana o de carga"], ["Context", "Contexto", "Device, location and risk", "Dispositivo, ubicación y riesgo"], ["Resource", "Recurso", "Explicitly protected asset", "Activo protegido explícitamente"], ["Decision", "Decisión", "Continuous least-privilege access", "Acceso continuo de mínimo privilegio"]], "Trust is evaluated for each access request and revisited as context changes.", "La confianza se evalúa para cada solicitud y se revisa cuando cambia el contexto."),
  diagram("attack-path", "Attack path interruption", "Interrupción de rutas de ataque", [["Initial access", "Acceso inicial", "Entry opportunity", "Oportunidad de entrada"], ["Privilege", "Privilegio", "Gain broader authority", "Obtener mayor autoridad"], ["Movement", "Movimiento", "Reach more assets", "Alcanzar más activos"], ["Objective", "Objetivo", "Cause impact or steal data", "Causar impacto o robar datos"]], "Prevention, detection and containment can interrupt the chain at multiple points.", "Prevención, detección y contención pueden interrumpir la cadena en varios puntos."),
  diagram("backup-flow", "Recoverable backup flow", "Flujo de copias recuperables", [["Production", "Producción", "Protected source data", "Datos de origen protegidos"], ["Backup", "Copia", "Isolated and versioned", "Aislada y versionada"], ["Validation", "Validación", "Integrity and malware checks", "Comprobaciones de integridad y malware"], ["Restore", "Restauración", "Tested business service", "Servicio de negocio probado"]], "A backup has value only when restoration is controlled, tested and timely.", "Una copia solo tiene valor cuando la restauración es controlada, probada y oportuna.")
];

const table = (id: string, en: string, es: string, rows: string[][]): ComparisonTable => ({ id, title: l(en, es), columns: [l("Approach", "Enfoque"), l("Primary purpose", "Finalidad principal"), l("Key consideration", "Consideración clave")], rows: rows.map(row => [l(row[0], row[1]), l(row[2], row[3]), l(row[4], row[5])]) });
export const comparisons: ComparisonTable[] = [
  table("aaa", "Authentication, authorisation and accounting", "Autenticación, autorización y registro", [["Authentication", "Autenticación", "Prove identity", "Demostrar identidad", "Strength and context", "Fortaleza y contexto"], ["Authorisation", "Autorización", "Permit actions", "Permitir acciones", "Least privilege", "Mínimo privilegio"], ["Accounting", "Registro", "Create accountability", "Crear trazabilidad", "Reliable audit events", "Eventos de auditoría fiables"]]),
  table("rbac-abac", "RBAC and ABAC", "RBAC y ABAC", [["RBAC", "RBAC", "Access by role", "Acceso por rol", "Simple governance; role growth", "Gobierno sencillo; proliferación de roles"], ["ABAC", "ABAC", "Access by attributes and policy", "Acceso por atributos y política", "Flexible; policy complexity", "Flexible; complejidad de políticas"]]),
  table("tcp-udp", "TCP and UDP", "TCP y UDP", [["TCP", "TCP", "Reliable ordered transport", "Transporte fiable y ordenado", "State and handshake", "Estado y negociación"], ["UDP", "UDP", "Low-overhead datagrams", "Datagramas de baja sobrecarga", "Application handles reliability", "La aplicación gestiona la fiabilidad"]]),
  table("ids-ips-ndr", "Network detection controls", "Controles de detección de red", [["IDS", "IDS", "Detect suspicious activity", "Detectar actividad sospechosa", "Usually out of band", "Normalmente fuera de banda"], ["IPS", "IPS", "Detect and block inline", "Detectar y bloquear en línea", "Availability and false blocks", "Disponibilidad y falsos bloqueos"], ["NDR", "NDR", "Analyse network behaviour", "Analizar comportamiento de red", "Telemetry coverage and context", "Cobertura de telemetría y contexto"]]),
  table("crypto", "Encryption, hashing and tokenisation", "Cifrado, hashing y tokenización", [["Encryption", "Cifrado", "Reversible confidentiality", "Confidencialidad reversible", "Key protection", "Protección de claves"], ["Hashing", "Hashing", "One-way integrity representation", "Representación unidireccional de integridad", "Algorithm and salting", "Algoritmo y sal"], ["Encoding", "Codificación", "Represent data format", "Representar el formato", "Not a security control", "No es un control de seguridad"], ["Tokenisation", "Tokenización", "Replace sensitive value", "Sustituir valor sensible", "Secure mapping system", "Sistema de correspondencia seguro"]]),
  table("cloud-models", "Cloud service models", "Modelos de servicio en la nube", [["IaaS", "IaaS", "Virtual infrastructure", "Infraestructura virtual", "Customer manages OS and above", "El cliente gestiona SO y capas superiores"], ["PaaS", "PaaS", "Managed application platform", "Plataforma de aplicación gestionada", "Customer manages code and data", "El cliente gestiona código y datos"], ["SaaS", "SaaS", "Complete software service", "Servicio software completo", "Customer manages use, identity and data", "El cliente gestiona uso, identidad y datos"]]),
  table("security-testing", "Application security testing", "Pruebas de seguridad de aplicaciones", [["SAST", "SAST", "Analyse source or build artefacts", "Analizar código o artefactos", "Early feedback; needs context", "Información temprana; necesita contexto"], ["DAST", "DAST", "Test running application", "Probar aplicación en ejecución", "Runtime view; limited code insight", "Visión del comportamiento en ejecución; poco detalle del código"], ["SCA", "SCA", "Inventory dependencies", "Inventariar dependencias", "Version and reachability context", "Contexto de versión y alcanzabilidad"]]),
  table("continuity", "Backup, DR, continuity and resilience", "Copia, DR, continuidad y resiliencia", [["Backup", "Copia", "Retain recoverable data", "Conservar datos recuperables", "Restore validation", "Validación de restauración"], ["Disaster recovery", "Recuperación ante desastres", "Restore technology services", "Restaurar servicios tecnológicos", "RTO and RPO", "RTO y RPO"], ["Business continuity", "Continuidad de negocio", "Maintain priority operations", "Mantener operaciones prioritarias", "People, sites and suppliers", "Personas, sedes y proveedores"], ["Resilience", "Resiliencia", "Withstand, recover and adapt", "Resistir, recuperar y adaptarse", "End-to-end dependencies", "Dependencias de extremo a extremo"]]),
  table("it-ot", "IT and OT priorities", "Prioridades de IT y OT", [["IT", "IT", "Information processing", "Procesamiento de información", "Rapid change can be feasible", "El cambio rápido puede ser viable"], ["OT", "OT", "Safe physical operation", "Operación física segura", "Change requires engineering validation", "El cambio requiere validación de ingeniería"]]),
  table("risk", "Inherent and residual risk", "Riesgo inherente y residual", [["Inherent", "Inherente", "Risk before selected controls", "Riesgo antes de controles seleccionados", "Supports control design", "Ayuda a diseñar controles"], ["Residual", "Residual", "Risk after control effects", "Riesgo tras el efecto de controles", "Requires acceptance or more treatment", "Requiere aceptación o más tratamiento"]])
];

const checklist = (id: string, en: string, es: string, items: string[][]): DefensiveChecklist => ({ id, title: l(en, es), items: items.map(([a,b]) => l(a,b)), note: l("Use this as a reference for review, not as evidence of completion.", "Úsalo como referencia para la revisión, no como evidencia de finalización.") });
export const checklists: DefensiveChecklist[] = [
  checklist("endpoint", "Endpoint hardening reference", "Referencia de bastionado de equipos", [["Remove unsupported or unnecessary software", "Retirar software sin soporte o innecesario"], ["Apply a tested secure baseline", "Aplicar una línea base segura y probada"], ["Protect administrative access", "Proteger el acceso administrativo"], ["Enable useful endpoint and audit telemetry", "Activar telemetría útil de los equipos y de auditoría"], ["Verify patch and encryption status", "Verificar parcheo y cifrado"]]),
  checklist("server", "Server hardening reference", "Referencia de bastionado de servidores", [["Define a minimal server role", "Definir un rol mínimo del servidor"], ["Restrict management paths", "Restringir vías de administración"], ["Use named privileged identities", "Usar identidades privilegiadas nominativas"], ["Monitor configuration drift", "Monitorizar desviaciones de configuración"], ["Test recovery before production", "Probar la recuperación antes de producción"]]),
  checklist("cloud", "Cloud configuration review", "Revisión de configuración en la nube", [["Inventory accounts, subscriptions and owners", "Inventariar cuentas, suscripciones y responsables"], ["Centralise identity and strong authentication", "Centralizar identidad y autenticación robusta"], ["Restrict public exposure by default", "Restringir la exposición pública por defecto"], ["Protect keys, secrets and logs", "Proteger claves, secretos y registros"], ["Test backup and recovery paths", "Probar vías de copia y recuperación"]]),
  checklist("identity", "Identity control review", "Revisión de controles de identidad", [["Use phishing-resistant MFA where appropriate", "Usar MFA resistente al phishing cuando proceda"], ["Separate routine and administrative identities", "Separar identidades de uso diario y administrativas"], ["Review dormant and service accounts", "Revisar cuentas inactivas y de servicio"], ["Limit session lifetime by risk", "Limitar duración de sesión según riesgo"], ["Monitor high-impact identity changes", "Monitorizar cambios de identidad de alto impacto"]]),
  checklist("network", "Network boundary review", "Revisión de límites de red", [["Document trust zones and allowed flows", "Documentar zonas de confianza y flujos permitidos"], ["Deny unnecessary paths", "Denegar vías innecesarias"], ["Protect and monitor name resolution", "Proteger y monitorizar la resolución de nombres"], ["Use secure remote access with strong identity", "Usar acceso remoto seguro con identidad robusta"], ["Validate detection visibility", "Validar la visibilidad de detección"]]),
  checklist("application", "Secure delivery reference", "Referencia de entrega segura", [["Model threats and abuse cases", "Modelar amenazas y casos de abuso"], ["Keep secrets out of source", "Mantener secretos fuera del código"], ["Review dependencies and provenance", "Revisar dependencias y procedencia"], ["Test authorisation on every sensitive action", "Probar autorización en cada acción sensible"], ["Make security events observable", "Hacer observables los eventos de seguridad"]]),
  checklist("ot", "OT defensive review", "Revisión defensiva de OT", [["Maintain a passive, owned asset inventory", "Mantener un inventario de activos pasivo y con responsable"], ["Broker and time-limit vendor access", "Intermediar y limitar temporalmente el acceso de proveedores"], ["Separate enterprise and control zones", "Separar zonas empresariales y de control"], ["Validate changes with engineering and safety", "Validar cambios con ingeniería y seguridad física"], ["Prepare safe manual fallback and recovery", "Preparar respaldo manual y recuperación seguros"]]),
  checklist("incident", "Incident preparation reference", "Referencia de preparación ante incidentes", [["Name decision-makers and alternates", "Designar responsables de decisión y suplentes"], ["Protect out-of-band communications", "Proteger comunicaciones fuera de banda"], ["Know evidence and legal requirements", "Conocer requisitos de evidencia y legales"], ["Pre-authorise proportionate containment", "Preautorizar contención proporcionada"], ["Exercise restoration and public communication", "Ensayar restauración y comunicación pública"]]),
  checklist("backup", "Recoverable backup reference", "Referencia de copias recuperables", [["Align backups to business RPO", "Alinear copias con el RPO del negocio"], ["Keep isolated or immutable copies", "Mantener copias aisladas o inmutables"], ["Protect backup administration separately", "Proteger por separado la administración de copias"], ["Monitor failed or deleted backup jobs", "Monitorizar trabajos fallidos o eliminados"], ["Test complete service restoration", "Probar la restauración completa del servicio"]]),
  checklist("privacy", "Privacy-aware design reference", "Referencia de diseño respetuoso con la privacidad", [["State purpose before collection", "Definir la finalidad antes de recopilar"], ["Minimise fields, access and retention", "Minimizar campos, acceso y conservación"], ["Explain choices in clear language", "Explicar las opciones con lenguaje claro"], ["Protect data throughout its lifecycle", "Proteger datos durante su ciclo de vida"], ["Provide accountable deletion and correction", "Facilitar borrado y corrección trazables"]])
];

export const diagramById = (id?: string) => diagrams.find(item => item.id === id);
export const comparisonById = (id?: string) => comparisons.find(item => item.id === id);
export const checklistById = (id?: string) => checklists.find(item => item.id === id);
